apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-application
  labels:
    app: node-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-web
  template:
    metadata:
      labels:
        app: node-web
    spec:
      containers:
        - name: node11
          image: vikrammadhyasta/node:v1
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
