apiVersion: v1
kind: Service
metadata:
  name: node-hello-service
  labels:
    app: node-hello
spec:
  type: LoadBalancer    # or ClusterIP / NodePort
  selector:
    app: node-hello
  ports:
    - protocol: TCP
      port: 80          # external port
      targetPort: 3000  # container port
