apiVersion: v1
kind: Service
metadata:
  name: sample_static-node-express-web-application
  labels:
    app: node-web
spec:
  type: LoadBalancer    
  selector:
    app: node-web
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 3000  
